export interface CaptionCue {
  start: number;
  end: number;
  text: string;
}

export interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  kind?: string;
  name?: string;
}

export interface FetchCaptionCuesOptions {
  autoGenerated?: boolean;
  maxCharactersPerCue?: number;
}

export interface CaptionTracksMessage {
  source: 'Open_Translator';
  type: '__LST_CAPTION_TRACKS__';
  tracks: CaptionTrack[];
  videoId: string | null;
  isLive: boolean;
  error?: string;
}

interface Json3Segment {
  utf8?: string;
}

interface Json3Event {
  tStartMs?: number;
  dDurationMs?: number;
  segs?: Json3Segment[];
  aAppend?: number;
}

interface Json3Payload {
  events?: Json3Event[];
}

const ASR_DEFAULT_MAX_MERGED_CHARS = 180;
const ASR_MAX_MERGED_DURATION_SECONDS = 4.5;
const ASR_MAX_MERGE_GAP_SECONDS = 0.8;
const ASR_SENTENCE_END_RE = /[.!?。！？…]["'”’)\]]*$/;
const MAX_CAPTION_TRACKS = 80;
const MAX_TRACK_URL_LENGTH = 8000;
const MAX_TRACK_FIELD_LENGTH = 256;

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null;
}

function isShortString(value: unknown, maxLength = MAX_TRACK_FIELD_LENGTH) {
  return typeof value === 'string' && value.length <= maxLength;
}

function isAllowedYoutubeHost(hostname: string) {
  const host = hostname.toLowerCase();
  return host === 'youtube.com' || host.endsWith('.youtube.com');
}

export function getAllowedTimedtextUrl(value: string): URL {
  if (value.length === 0 || value.length > MAX_TRACK_URL_LENGTH) {
    throw new Error('caption URL length is invalid');
  }

  const url = new URL(value, location.origin);
  const allowedPath =
    url.pathname === '/api/timedtext' ||
    url.pathname.endsWith('/api/timedtext') ||
    url.pathname === '/timedtext' ||
    url.pathname === '/youtubei/v1/get_transcript';

  if (
    url.protocol !== 'https:' ||
    !isAllowedYoutubeHost(url.hostname) ||
    !allowedPath
  ) {
    throw new Error('caption URL is not a YouTube timedtext endpoint');
  }

  return url;
}

function isAllowedTimedtextUrl(value: unknown) {
  if (typeof value !== 'string') return false;
  try {
    getAllowedTimedtextUrl(value);
    return true;
  } catch {
    return false;
  }
}

function isCaptionTrack(value: unknown): value is CaptionTrack {
  if (!isRecord(value)) return false;
  if (!isAllowedTimedtextUrl(value.baseUrl)) return false;
  if (!isShortString(value.languageCode, 48)) return false;
  if (value.kind !== undefined && !isShortString(value.kind, 48)) return false;
  if (value.name !== undefined && !isShortString(value.name)) return false;
  return true;
}

export function isCaptionTracksMessage(value: unknown): value is CaptionTracksMessage {
  if (!isRecord(value)) return false;
  if (value.source !== 'Open_Translator') return false;
  if (value.type !== '__LST_CAPTION_TRACKS__') return false;
  if (!Array.isArray(value.tracks)) return false;
  if (value.tracks.length > MAX_CAPTION_TRACKS) return false;
  if (!value.tracks.every(isCaptionTrack)) return false;
  if (value.videoId !== null && !isShortString(value.videoId, 128)) return false;
  if (typeof value.isLive !== 'boolean') return false;
  if (value.error !== undefined && !isShortString(value.error, 1000)) return false;
  return true;
}

export function pickCaptionTrack(
  tracks: CaptionTrack[],
  preferredLanguage = 'en',
): CaptionTrack | null {
  if (tracks.length === 0) return null;

  const prefix = preferredLanguage.toLowerCase().slice(0, 2);
  const byLang = (t: CaptionTrack) =>
    typeof t.languageCode === 'string' &&
    t.languageCode.toLowerCase().startsWith(prefix);

  const manualPreferred = tracks.find((t) => !t.kind && byLang(t));
  if (manualPreferred) return manualPreferred;

  const asrPreferred = tracks.find((t) => t.kind === 'asr' && byLang(t));
  if (asrPreferred) return asrPreferred;

  const anyManual = tracks.find((t) => !t.kind);
  if (anyManual) return anyManual;

  return tracks[0] ?? null;
}

function eventText(event: Json3Event): string {
  if (!Array.isArray(event.segs)) return '';
  return event.segs
    .map((s) => (typeof s.utf8 === 'string' ? s.utf8 : ''))
    .join('');
}

function normalizeCueText(text: string): string {
  return text.replace(/\s+/g, ' ').trim();
}

function hasSentenceEnding(text: string): boolean {
  return ASR_SENTENCE_END_RE.test(text.trim());
}

function mergeOverlappingText(current: string, next: string): string {
  const currentWords = current.split(/\s+/).filter(Boolean);
  const nextWords = next.split(/\s+/).filter(Boolean);
  const maxOverlap = Math.min(8, currentWords.length, nextWords.length);

  for (let size = maxOverlap; size > 0; size -= 1) {
    const currentTail = currentWords.slice(-size).join(' ').toLowerCase();
    const nextHead = nextWords.slice(0, size).join(' ').toLowerCase();
    if (currentTail === nextHead) {
      return [...currentWords, ...nextWords.slice(size)].join(' ');
    }
  }

  return `${current} ${next}`.trim();
}

export function normalizeAutoGeneratedCues(
  cues: CaptionCue[],
  maxMergedChars = ASR_DEFAULT_MAX_MERGED_CHARS,
): CaptionCue[] {
  const maxChars = Math.max(40, maxMergedChars);
  const sorted = cues
    .map((cue) => ({
      ...cue,
      text: normalizeCueText(cue.text),
    }))
    .filter((cue) => cue.text.length > 0)
    .sort((a, b) => a.start - b.start);

  const merged: CaptionCue[] = [];
  let current: CaptionCue | null = null;

  for (const cue of sorted) {
    if (!current) {
      current = cue;
      continue;
    }

    const gap = cue.start - current.end;
    const combinedText = normalizeCueText(
      mergeOverlappingText(current.text, cue.text),
    );
    const combinedEnd = Math.max(current.end, cue.end);
    const combinedDuration = combinedEnd - current.start;

    const shouldStartNewCue =
      gap > ASR_MAX_MERGE_GAP_SECONDS ||
      hasSentenceEnding(current.text) ||
      combinedText.length > maxChars ||
      combinedDuration > ASR_MAX_MERGED_DURATION_SECONDS;

    if (shouldStartNewCue) {
      merged.push(current);
      current = cue;
      continue;
    }

    current = {
      start: current.start,
      end: combinedEnd,
      text: combinedText,
    };
  }

  if (current) {
    merged.push(current);
  }

  return merged;
}

function prepareFetchedCues(
  cues: CaptionCue[],
  options?: FetchCaptionCuesOptions,
): CaptionCue[] {
  if (!options?.autoGenerated) {
    return cues;
  }

  const normalized = normalizeAutoGeneratedCues(
    cues,
    options.maxCharactersPerCue,
  );
  console.log(
    '[LST] normalized ASR cues raw=' +
      cues.length +
      ' merged=' +
      normalized.length,
  );
  return normalized;
}

export function parseJson3(payload: unknown): CaptionCue[] {
  if (!isRecord(payload)) return [];
  const events = (payload as Json3Payload).events;
  if (!Array.isArray(events)) return [];

  const cues: CaptionCue[] = [];
  for (const event of events) {
    if (event.aAppend === 1) {
      const last = cues[cues.length - 1];
      if (!last) continue;
      const appended = eventText(event);
      if (!appended) continue;
      const merged = (last.text + ' ' + appended).replace(/\s+/g, ' ').trim();
      const appendStartMs = event.tStartMs;
      const appendDurationMs = event.dDurationMs;
      const appendedEnd =
        typeof appendStartMs === 'number' &&
        typeof appendDurationMs === 'number' &&
        appendDurationMs > 0
          ? (appendStartMs + appendDurationMs) / 1000
          : last.end;
      cues[cues.length - 1] = {
        ...last,
        end: Math.max(last.end, appendedEnd),
        text: merged,
      };
      continue;
    }

    const startMs = event.tStartMs;
    const durationMs = event.dDurationMs;
    if (typeof startMs !== 'number' || typeof durationMs !== 'number') continue;
    if (durationMs <= 0) continue;

    const text = eventText(event).replace(/\s+/g, ' ').trim();
    if (!text) continue;

    cues.push({
      start: startMs / 1000,
      end: (startMs + durationMs) / 1000,
      text,
    });
  }

  cues.sort((a, b) => a.start - b.start);
  return cues;
}

function decodeEntities(value: string): string {
  return value
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&nbsp;/g, ' ');
}

function extractElementText(element: Element): string {
  const raw = element.textContent ?? '';
  return decodeEntities(raw).replace(/\s+/g, ' ').trim();
}

export function parseXmlCaptions(xml: string): CaptionCue[] {
  let doc: Document;
  try {
    doc = new DOMParser().parseFromString(xml, 'application/xml');
  } catch {
    return [];
  }

  if (doc.getElementsByTagName('parsererror').length > 0) {
    return [];
  }

  const cues: CaptionCue[] = [];

  const pElements = doc.querySelectorAll('p');
  for (const p of Array.from(pElements)) {
    const t = p.getAttribute('t');
    const d = p.getAttribute('d');
    if (t === null || d === null) continue;
    const startMs = Number(t);
    const durationMs = Number(d);
    if (!Number.isFinite(startMs) || !Number.isFinite(durationMs)) continue;
    if (durationMs <= 0) continue;
    const text = extractElementText(p);
    if (!text) continue;
    cues.push({
      start: startMs / 1000,
      end: (startMs + durationMs) / 1000,
      text,
    });
  }

  if (cues.length === 0) {
    const textElements = doc.querySelectorAll('text');
    for (const el of Array.from(textElements)) {
      const startAttr = el.getAttribute('start');
      const durAttr = el.getAttribute('dur');
      if (startAttr === null) continue;
      const start = Number(startAttr);
      const duration = Number(durAttr ?? '0');
      if (!Number.isFinite(start) || !Number.isFinite(duration)) continue;
      if (duration <= 0) continue;
      const text = extractElementText(el);
      if (!text) continue;
      cues.push({ start, end: start + duration, text });
    }
  }

  cues.sort((a, b) => a.start - b.start);
  return cues;
}

function parseCaptionBody(body: string): CaptionCue[] {
  const trimmed = body.trim();
  if (!trimmed) return [];
  if (trimmed.startsWith('{')) {
    try {
      return parseJson3(JSON.parse(trimmed));
    } catch {
      return [];
    }
  }
  if (trimmed.startsWith('<')) {
    return parseXmlCaptions(trimmed);
  }
  return [];
}

async function fetchTimedtextBody(
  baseUrl: string,
  fmt: string | null,
  signal: AbortSignal | undefined,
): Promise<string> {
  const url = getAllowedTimedtextUrl(baseUrl);
  if (fmt !== null) {
    url.searchParams.set('fmt', fmt);
  }

  const response = await fetch(url.toString(), {
    credentials: 'include',
    signal,
  });

  if (!response.ok) {
    throw new Error(`HTTP ${response.status}`);
  }

  return response.text();
}

function buildTrackMatcher(baseUrl: string): (url: string) => boolean {
  let target: URL | null = null;
  try {
    target = getAllowedTimedtextUrl(baseUrl);
  } catch {
    target = null;
  }
  const videoId = target?.searchParams.get('v') ?? null;
  const lang = target?.searchParams.get('lang') ?? null;
  const kind = target?.searchParams.get('kind') ?? '';

  return (candidate: string) => {
    let u: URL;
    try {
      u = getAllowedTimedtextUrl(candidate);
    } catch {
      return false;
    }
    if (videoId && u.searchParams.get('v') !== videoId) return false;
    if (lang && u.searchParams.get('lang') !== lang) return false;
    if ((u.searchParams.get('kind') ?? '') !== kind) return false;
    return true;
  };
}

export async function fetchCaptionCues(
  baseUrl: string,
  videoId: string | null,
  preferredLang: string,
  signal?: AbortSignal,
  options?: FetchCaptionCuesOptions,
): Promise<CaptionCue[]> {
  console.log(
    '[LST] fetchCaptionCues start videoId=' +
      (videoId ?? 'null') +
      ' lang=' +
      preferredLang,
  );
  const errors: string[] = [];

  // === Strategy 1: InnerTube ANDROID client (bypasses pot for ASR) ===
  if (videoId) {
    try {
      const { fetchCaptionsViaInnertube } = await import('./innertube.ts');
      const cues = await fetchCaptionsViaInnertube(
        videoId,
        preferredLang,
        signal,
      );
      console.log('[LST] innertube path OK cues=' + cues.length);
      return prepareFetchedCues(cues, options);
    } catch (err) {
      if (err instanceof DOMException && err.name === 'AbortError') throw err;
      const msg = err instanceof Error ? err.message : String(err);
      errors.push(`innertube: ${msg}`);
      console.log('[LST] innertube failed, falling back:', msg);
    }
  }

  // === Strategy 2: Intercept YouTube player's own signed fetch ===
  try {
    const { waitForInterceptedBody } = await import('./pageBridge.ts');
    const match = buildTrackMatcher(baseUrl);
    const body = await waitForInterceptedBody(match, 5000, signal);
    console.log('[LST] intercept hit, body len=' + body.length);
    const cues = parseCaptionBody(body);
    if (cues.length > 0) {
      console.log('[LST] intercept path OK cues=' + cues.length);
      return prepareFetchedCues(cues, options);
    }
    errors.push('intercept: 0 cues parsed');
  } catch (err) {
    if (err instanceof DOMException && err.name === 'AbortError') throw err;
    const msg = err instanceof Error ? err.message : String(err);
    errors.push(`intercept: ${msg}`);
    console.log('[LST] intercept failed, falling back:', msg);
  }

  // === Strategy 3: Direct fetch with fmt fallback chain (legacy) ===
  const attempts: Array<string | null> = ['json3', 'srv3', 'srv1', null];

  for (const fmt of attempts) {
    try {
      const body = await fetchTimedtextBody(baseUrl, fmt, signal);
      const trimmed = body.trim();
      if (!trimmed) {
        errors.push(`direct fmt=${fmt ?? 'default'}: empty body`);
        continue;
      }
      const cues = parseCaptionBody(trimmed);
      if (cues.length > 0) {
        console.log(
          '[LST] direct path OK fmt=' +
            (fmt ?? 'default') +
            ' cues=' +
            cues.length,
        );
        return prepareFetchedCues(cues, options);
      }
      errors.push(`direct fmt=${fmt ?? 'default'}: 0 cues`);
    } catch (err) {
      if (err instanceof DOMException && err.name === 'AbortError') throw err;
      const msg = err instanceof Error ? err.message : String(err);
      errors.push(`direct fmt=${fmt ?? 'default'}: ${msg}`);
    }
  }

  throw new Error(`all strategies failed — ${errors.join(' | ')}`);
}

export function findActiveCueIndex(
  cues: CaptionCue[],
  currentTime: number,
  previousIndex: number,
): number {
  if (cues.length === 0) return -1;

  if (previousIndex >= 0 && previousIndex < cues.length) {
    const current = cues[previousIndex];
    if (current && currentTime >= current.start && currentTime < current.end) {
      return previousIndex;
    }
    const next = cues[previousIndex + 1];
    if (next && currentTime >= next.start && currentTime < next.end) {
      return previousIndex + 1;
    }
  }

  let low = 0;
  let high = cues.length - 1;
  while (low <= high) {
    const mid = (low + high) >> 1;
    const cue = cues[mid];
    if (!cue) break;
    if (currentTime < cue.start) {
      high = mid - 1;
    } else if (currentTime >= cue.end) {
      low = mid + 1;
    } else {
      return mid;
    }
  }

  return -1;
}
